[workspace]
resolver = "3"
members = [
    "android_deploy",
    "bios_bootloader_common",
    "bios_bootloader_big_stage",
    "bios_bootloader_small_stage",
    "kernel_uefi",
    "mbr_bootloader",
    "scripts",
]

[workspace.package]
version = "1.0.0"
edition = "2024"

[workspace.dependencies]
acpi = { git = "https://github.com/ChocolateLoverRaj/acpi", branch = "fearless_os", default-features = false }
arbitrary-int = { version = "2.1.1", default-features = false }
bios_bootloader_common = { path = "bios_bootloader_common", default-features = false }
bitbybit = { version = "2.0.1", default-features = false }
clap = { version = "4.6.6", default-features = false }
elf = { version = "0.8.0", default-features = false }
embedded-graphics = { version = "0.8.2", default-features = false }
ez_ehci = { path = "../ez_ehci", default-features = false }
ez_hpet = { path = "../ez_hpet", default-features = false }
ez_pci = { path = "../ez_pci", default-features = false }
force-send-sync = { version = "2.0.0", default-features = false }
futures = { version = "0.3.34", default-features = false }
gptman = { version = "3.1.1", default-features = false }
heapless = { version = "0.9.3", default-features = false }
log = { version = "0.4.34", default-features = false }
mbrman = { version = "0.6.1", default-features = false }
nodit = { version = "0.10.0", default-features = false }
owo-colors = { version = "4.4.0", default-features = false }
pic8259 = { version = "0.11.0", default-features = false }
raw-cpuid = { version = "11.6.0", default-features = false }
spin = { version = "0.12.2", default-features = false }
spinning_top = { version = "0.3.0", default-features = false }
talc = { version = "5.0.4", default-features = false }
uart_16550 = { version = "0.8.0", default-features = false }
uefi = { version = "0.40.0", default-features = false }
unicode-segmentation = { version = "1.13.3", default-features = false }
x2apic = { git = "https://github.com/ChocolateLoverRaj/x2apic-rs", branch = "main", default-features = false }
x86_64 = { git = "https://github.com/rust-osdev/x86_64", branch = "next", default-features = false }
zerocopy = { version = "0.8.55", default-features = false }
