[package]
name = "kernel_uefi"
version.workspace = true
edition.workspace = true

[[bin]]
name = "kernel_uefi"
test = false
bench = false

[dependencies]
force-send-sync = { workspace = true }
log = { workspace = true }
kernel_common = { workspace = true, features = ["alloc"] }
spin = { workspace = true, features = ["once"] }
static_cell = { workspace = true }
uefi = { workspace = true }
x86_64 = { workspace = true, features = ["instructions"] }
