build_dir := "build"

[arg("accel", long="accel", short="a", value="y")]
run accel='':
    mkdir -p {{ build_dir }}/EFI/BOOT
    cargo build --target x86_64-unknown-uefi
    ln -sf ../../../target/x86_64-unknown-uefi/debug/kernel_uefi.efi {{ build_dir }}/EFI/BOOT/BOOTX64.EFI
    qemu-system-x86_64 -enable-kvm \
        -machine q35,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        -drive if=pflash,format=raw,readonly=on,file=$OVMF_PATH \
        -drive format=raw,file=fat:rw:{{ build_dir }} \
        -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock \
        -tpmdev emulator,id=tpm0,chardev=chrtpm \
        -device tpm-tis,tpmdev=tpm0 \
        --nographic

swtpm:
    swtpm socket --tpmstate dir=/tmp/mytpm1 \
        --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock \
        --tpm2 \
        --log level=20

hash:
    pesign --hash -i build/EFI/BOOT/BOOTX64.EFI --digest-type sha256
