build_dir := "build"
build_dir_x86_64 := build_dir + "/x86_64"
build_dir_uefi := build_dir + "/uefi"
build_dir_aarch64 := build_dir + "/aarch64"
build_dir_arm := build_dir + "/arm"
build_dir_riscv64 := build_dir + "/riscv"
kernel_file_name := "kernel.img"
build_dir_bios := build_dir + "/bios"

[arg("accel", long="accel", short="a", value="y")]
[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("release", long="release", short="r", value="y")]
[arg("stop", long="stop", short="S", value="y")]
x86_64 accel='' release='' stop='' no_graphic='':
    @echo {{ release }}
    mkdir {{ build_dir_x86_64 }}/EFI/BOOT -p
    ln -sf $LIMINE_PATH/BOOTX64.EFI {{ build_dir_x86_64 }}/EFI/BOOT/BOOTX64.EFI
    ln -sf ../../limine.conf {{ build_dir_x86_64 }}/limine.conf
    cargo build --target x86_64-unknown-none {{ if release == 'y' { '--release' } else { '' } }}
    ln -sf ../../target/x86_64-unknown-none/{{ if release == 'y' { 'release' } else { 'debug' } }}/kernel {{ build_dir_x86_64 }}/kernel
    # Support acceleration on Linux (kvm), Windows (whpx), MacOS (hvf), falling back to software (tcg) virtualization.
    qemu-system-x86_64 \
        -machine q35,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        -bios $OVMF_PATH \
        -drive format=raw,file=fat:rw:{{ build_dir_x86_64 }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic' } else { '' } }}

[arg("accel", long="accel", short="a", value="y")]
uefi accel='':
    mkdir -p {{ build_dir_uefi }}/EFI/BOOT
    cargo build --target x86_64-unknown-uefi
    ln -sf ../../../../target/x86_64-unknown-uefi/debug/kernel.efi {{ build_dir_uefi }}/EFI/BOOT/BOOTX64.EFI
    qemu-system-x86_64 -enable-kvm \
        -machine q35,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        -drive if=pflash,format=raw,readonly=on,file=$OVMF_PATH \
        -drive format=raw,file=fat:rw:{{ build_dir_uefi }} \
        -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock \
        -tpmdev emulator,id=tpm0,chardev=chrtpm \
        -device tpm-tis,tpmdev=tpm0 \
        --nographic

swtpm:
    mkdir -p /tmp/mytpm1
    swtpm socket --tpmstate dir=/tmp/mytpm1 \
        --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock \
        --tpm2 \
        --log level=20

hash:
    pesign --hash -i {{ build_dir_uefi }}/EFI/BOOT/BOOTX64.EFI --digest-type sha256

[arg("accel", long="accel", short="a", value="y")]
[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("release", long="release", short="r", value="y")]
[arg("stop", long="stop", short="S", value="y")]
aarch64 accel='' release='' stop='' no_graphic='':
    mkdir -p {{ build_dir_aarch64 }}
    cargo objcopy --target aarch64-unknown-none-softfloat {{ if release == 'y' { '--release' } else { '' } }} -- -O binary {{ build_dir_aarch64 }}/{{ kernel_file_name }}
    qemu-system-aarch64 \
        --machine raspi3b,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        --no-reboot \
        --kernel {{ build_dir_aarch64 }}/{{ kernel_file_name }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic --serial none --serial mon:stdio' } else { '' } }} \
        -d int \
        -D {{ build_dir_aarch64 }}/qemu.log

[arg("accel", long="accel", short="a", value="y")]
[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("release", long="release", short="r", value="y")]
[arg("stop", long="stop", short="S", value="y")]
raspi0 accel='' release='' stop='' no_graphic='':
    mkdir -p {{ build_dir_arm }}
    cargo objcopy --target armv6-none-eabihf {{ if release == 'y' { '--release' } else { '' } }} -- -O binary {{ build_dir_arm }}/{{ kernel_file_name }}
    qemu-system-arm \
        --machine raspi0,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        --no-reboot \
        --kernel {{ build_dir_arm }}/{{ kernel_file_name }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic --serial mon:stdio' } else { '' } }} \
        -d int \
        -D {{ build_dir_arm }}/qemu.log

[arg("accel", long="accel", short="a", value="y")]
[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("release", long="release", short="r", value="y")]
[arg("stop", long="stop", short="S", value="y")]
raspi1ap accel='' release='' stop='' no_graphic='':
    mkdir -p {{ build_dir_arm }}
    cargo objcopy --target armv6-none-eabihf {{ if release == 'y' { '--release' } else { '' } }} -- -O binary {{ build_dir_arm }}/{{ kernel_file_name }}
    qemu-system-arm \
        --machine raspi1ap,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        --no-reboot \
        --kernel {{ build_dir_arm }}/{{ kernel_file_name }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic --serial mon:stdio' } else { '' } }} \
        -d int \
        -D {{ build_dir_arm }}/qemu.log

[arg("accel", long="accel", short="a", value="y")]
[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("release", long="release", short="r", value="y")]
[arg("stop", long="stop", short="S", value="y")]
raspi2b accel='' release='' stop='' no_graphic='':
    mkdir -p {{ build_dir_arm }}
    cargo objcopy --target armv6-none-eabihf {{ if release == 'y' { '--release' } else { '' } }} -- -O binary {{ build_dir_arm }}/{{ kernel_file_name }}
    qemu-system-arm \
        --machine raspi2b,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        --no-reboot \
        --kernel {{ build_dir_arm }}/{{ kernel_file_name }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic --serial mon:stdio' } else { '' } }} \
        -d int \
        -D {{ build_dir_arm }}/qemu.log

[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("stop", long="stop", short="S", value="y")]
riscv64 accel='' release='' stop='' no_graphic='':
    mkdir -p {{ build_dir_riscv64 }}
    cargo objcopy --target riscv64gc-unknown-none-elf {{ if release == 'y' { '--release' } else { '' } }} -- -O binary {{ build_dir_riscv64 }}/{{ kernel_file_name }}
    qemu-system-riscv64 \
        --machine virt,accel={{ if accel == 'y' { 'kvm:tcg' } else { 'tcg' } }} \
        --no-reboot \
        --kernel {{ build_dir_riscv64 }}/{{ kernel_file_name }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic --serial mon:stdio' } else { '' } }} \
        --smp 1

dtb:
    mkdir -p {{ build_dir_riscv64 }}
    qemu-system-riscv64 --machine virt,dumpdtb={{ build_dir_riscv64 }}/virt.dtb \
        --smp 4
    dtc -I dtb -O dts -o {{ build_dir_riscv64 }}/virt.dts {{ build_dir_riscv64 }}/virt.dtb

build_bios:
    mkdir -p {{ build_dir_bios }}

    # Create the disk file
    # We need 33 MiB minimum to create a minimum sized FAT32 partition within it
    # We are using 65 MiB to create a larger FAT32 partition which will have 2 sectors per cluster for testing
    truncate -s 65M {{ build_dir_bios }}/disk.img

    # Format the disk as GPT with a FAT32 partition
    parted {{ build_dir_bios }}/disk.img --script \
      mklabel gpt \
      mkpart "BOOT" fat32 1MiB 100% \
      set 1 legacy_boot on

    # Install the BIOS code that goes in the protective MBR
    nasm -f bin stage0.S -o {{ build_dir_bios }}/stage0.bin
    nasm -f bin stage1.S -o {{ build_dir_bios }}/stage1.bin -DSTAGE_0_SIZE=$(stat -c %s {{ build_dir_bios }}/stage0.bin)
    cat {{ build_dir_bios }}/stage0.bin {{ build_dir_bios }}/stage1.bin > {{ build_dir_bios }}/mbr.bin
    @test $(stat -c %s {{ build_dir_bios }}/mbr.bin) -le 440 \
            || (echo "mbr.bin exceeds 440 bytes" && exit 1)
    dd if={{ build_dir_bios }}/mbr.bin of={{ build_dir_bios }}/disk.img bs=440 conv=notrunc

    # Format the FAT32 partition
    # 2 sectors per cluster to test our loading code
    # 2048 hidden sectors, because our FAT32 partition starts at sector 2048
    # Size of FAT32 partition, in sectors
    # Format at FAT32
    # Label it as "BOOT"
    mformat -i {{ build_dir_bios }}/disk.img@@1M -c 2 -H 2048 -T 131039 -F -v BOOT ::

    # Install the BIOS code that goes into the FAT32's BIOS boot section
    nasm -f bin bios_fat32_0.S -o {{ build_dir_bios }}/bios_fat32_0.bin
    @test $(stat -c %s {{ build_dir_bios }}/bios_fat32_0.bin) -le 3 \
            || (echo "bios_fat32_0.bin exceeds 3 bytes" && exit 1)
    nasm -f bin bios_fat32_1.S -o {{ build_dir_bios }}/bios_fat32_1.bin
    @test $(stat -c %s {{ build_dir_bios }}/bios_fat32_1.bin) -le 420 \
            || (echo "bios_fat32_1.bin exceeds 420 bytes" && exit 1)
    dd if={{ build_dir_bios }}/bios_fat32_0.bin of={{ build_dir_bios }}/disk.img bs=1M seek=1 conv=notrunc
    dd if={{ build_dir_bios }}/bios_fat32_1.bin of={{ build_dir_bios }}/disk.img bs=1 seek=1048666 conv=notrunc

    # Add the BIOS boot file
    nasm -f bin boot.S -o {{ build_dir_bios }}/BOOT.BIN
    # 512 B in a sector
    # 32 B per entry
    # 16 entries per sector
    # One entry for volume ID before BOOT.BIN
    # Create extra entries before the BOOT.BIN entry to test our loader searching further
    # Add 15 items to make BOOT.BIN get placed in sector 1 of the cluster
    # Add 31 items to make BOOT.BIN get placed in cluster 1 of the file
    for i in {0..30}; do mcopy -i {{ build_dir_bios }}/disk.img@@1M /dev/null ::TEST_$i; done
    # Add a dir to create a gap between the first and second root dir clusters
    mmd -i {{ build_dir_bios }}/disk.img@@1M ::TEST_DIR
    mcopy -i {{ build_dir_bios }}/disk.img@@1M {{ build_dir_bios }}/BOOT.BIN ::

bios: build_bios
    qemu-system-x86_64 \
        --machine q35,accel=kvm:whpx:hvf:tcg \
        --no-reboot \
        --nographic \
        -drive file={{ build_dir_bios }}/disk.img,format=raw,if=ide,snapshot=on \
        -d int,cpu_reset,guest_errors \
        -D {{ build_dir_bios }}/qemu.log

bios_q35: build_bios
    qemu-system-x86_64 \
       --machine q35,accel=kvm:whpx:hvf:tcg \
       --no-reboot \
       --nographic \
       -drive file={{ build_dir_bios }}/disk.img,format=raw,if=ide,snapshot=on
