build_dir := "build"
build_dir_x86_64 := build_dir + "/x86_64"
build_dir_uefi := build_dir + "/uefi"
build_dir_aarch64 := build_dir + "/aarch64"
build_dir_riscv64 := build_dir + "/riscv"
kernel_file_name := "kernel.img"

[arg("accel", long="accel", short="a", value="y")]
[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("release", long="release", short="r", value="y")]
[arg("stop", long="stop", short="S", value="y")]
x86_64 accel='' release='' stop='' no_graphic='':
    @echo {{ release }}
    mkdir {{ build_dir_x86_64 }}/EFI/BOOT -p
    ln -sf $LIMINE_PATH/BOOTX64.EFI {{ build_dir_x86_64 }}/EFI/BOOT/BOOTX64.EFI
    ln -sf ../../limine.conf {{ build_dir_x86_64 }}/limine.conf
    cargo build --target x86_64-unknown-none {{ if release == 'y' { '--release' } else { '' } }}
    ln -sf ../../target/x86_64-unknown-none/{{ if release == 'y' { 'release' } else { 'debug' } }}/kernel {{ build_dir_x86_64 }}/kernel
    # Support acceleration on Linux (kvm), Windows (whpx), MacOS (hvf), falling back to software (tcg) virtualization.
    qemu-system-x86_64 \
        -machine q35,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        -bios $OVMF_PATH \
        -drive format=raw,file=fat:rw:{{ build_dir_x86_64 }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic' } else { '' } }}

[arg("accel", long="accel", short="a", value="y")]
uefi accel='':
    mkdir -p {{ build_dir_uefi }}/EFI/BOOT
    cargo build --target x86_64-unknown-uefi
    ln -sf ../../../../target/x86_64-unknown-uefi/debug/kernel.efi {{ build_dir_uefi }}/EFI/BOOT/BOOTX64.EFI
    qemu-system-x86_64 -enable-kvm \
        -machine q35,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        -drive if=pflash,format=raw,readonly=on,file=$OVMF_PATH \
        -drive format=raw,file=fat:rw:{{ build_dir_uefi }} \
        -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock \
        -tpmdev emulator,id=tpm0,chardev=chrtpm \
        -device tpm-tis,tpmdev=tpm0 \
        --nographic

swtpm:
    mkdir -p /tmp/mytpm1
    swtpm socket --tpmstate dir=/tmp/mytpm1 \
        --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock \
        --tpm2 \
        --log level=20

hash:
    pesign --hash -i {{ build_dir_uefi }}/EFI/BOOT/BOOTX64.EFI --digest-type sha256

[arg("accel", long="accel", short="a", value="y")]
[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("release", long="release", short="r", value="y")]
[arg("stop", long="stop", short="S", value="y")]
aarch64 accel='' release='' stop='' no_graphic='':
    mkdir -p {{ build_dir_aarch64 }}
    cargo objcopy --target aarch64-unknown-none-softfloat {{ if release == 'y' { '--release' } else { '' } }} -- -O binary {{ build_dir_aarch64 }}/{{ kernel_file_name }}
    qemu-system-aarch64 \
        --machine raspi3b,accel={{ if accel == 'y' { 'kvm:whpx:hvf:tcg' } else { 'tcg' } }} \
        --no-reboot \
        --kernel {{ build_dir_aarch64 }}/{{ kernel_file_name }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic --serial none --serial mon:stdio' } else { '' } }} \
        -d int \
        -D {{ build_dir_aarch64 }}/qemu.log

[arg("accel", long="accel", short="a", value="y")]
[arg("no_graphic", long="no-graphic", short="n", value="y")]
[arg("release", long="release", short="r", value="y")]
[arg("stop", long="stop", short="S", value="y")]
riscv64 accel='' release='' stop='' no_graphic='':
    mkdir -p {{ build_dir_riscv64 }}
    cargo objcopy --target riscv64gc-unknown-none-elf {{ if release == 'y' { '--release' } else { '' } }} -- -O binary {{ build_dir_riscv64 }}/{{ kernel_file_name }}
    qemu-system-riscv64 \
        --machine virt,accel={{ if accel == 'y' { 'kvm:tcg' } else { 'tcg' } }} \
        --no-reboot \
        --kernel {{ build_dir_riscv64 }}/{{ kernel_file_name }} \
        -s \
        {{ if stop == 'y' { '-S' } else { '' } }} \
        {{ if no_graphic == 'y' { '--nographic --serial mon:stdio' } else { '' } }} \
        --smp 1

dtb:
    mkdir -p {{ build_dir_riscv64 }}
    qemu-system-riscv64 --machine virt,dumpdtb={{ build_dir_riscv64 }}/virt.dtb \
        --smp 4
    dtc -I dtb -O dts -o {{ build_dir_riscv64 }}/virt.dts {{ build_dir_riscv64 }}/virt.dtb
